services:
  nginx:
    image: nginx:latest
    container_name: nginx-bank
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./app:/var/www/html/
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php-bank
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
    - ./app:/var/www/html/
  mysql:
    container_name: mysql
    image: mysql:lts
    restart: always
    ports:
       - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_PASSWORD: '1234'
      MYSQL_USER: 'sa'
      MYSQL_DATABASE: 'bank'

    volumes:
      - ./db/:/var/lib/mysql